import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const documentsTable = sqliteTable(
  "documents",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    name: text("name").notNull(),
    mimeType: text("mime_type"),
    sizeBytes: integer("size_bytes"),
    contentHash: text("content_hash"),
    storageDriver: text("storage_driver").notNull(),
    storageKey: text("storage_key").notNull(),
    extractedText: text("extracted_text"),
    extractionStatus: text("extraction_status").notNull().default("pending"),
    extractionError: text("extraction_error"),
    ruleStatus: text("rule_status").notNull().default("pending"),
    ruleError: text("rule_error"),
    embeddingStatus: text("embedding_status").notNull().default("pending"),
    embeddingError: text("embedding_error"),
    summary: text("summary"),
    suggestedTitle: text("suggested_title"),
    summaryStatus: text("summary_status").notNull().default("pending"),
    summaryError: text("summary_error"),
    categoryId: text("category_id"),
    categorySource: text("category_source"),
    documentDate: text("document_date"),
    triageStatus: text("triage_status").notNull().default("pending"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => [
    index("documents_user_category_idx").on(t.userId, t.categoryId),
    index("documents_user_triage_idx").on(t.userId, t.triageStatus),
  ],
);
